import "dotenv/config"
import { PrismaClient } from "../src/generated/prisma"
import { PrismaPg } from "@prisma/adapter-pg"

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter }) as any

async function main() {
  // 1. Propunere PMA B2C — structura servicii + pricing
  const p1 = await prisma.orgProposal.create({
    data: {
      proposalType: "MODIFY_OBJECTIVES",
      status: "DRAFT",
      proposedBy: "CLAUDE",
      title: "B2C Structura servicii + propuneri pricing pe carduri",
      description: [
        "PMA (Product Manager B2C) + MKA + ACA + COG:",
        "",
        "TASK: Pe baza designului B2C complet (6 carduri, onboarding, comunitati, punte B2B), concepe:",
        "",
        "1. STRUCTURA DE SERVICII B2C — per card, ce e gratuit, ce e platit",
        "",
        "PRINCIPIU PRICING: 'Fiecare parte primeste gratuit ce-l aduce la masa, plateste ce-l ajuta sa castige.'",
        "",
        "CARDURI SI SERVICII:",
        "",
        "Card 6 (Profiler) — ACTIV BY DEFAULT, GRATUIT:",
        "  - Dialog initial + mini-chestionar",
        "  - Insight-uri de baza despre profil",
        "  - Platit: profil detaliat, evaluare VIA strengths (Niemec), plan dezvoltare",
        "",
        "Card 3 (Rol profesional) — ACTIV BY DEFAULT, GRATUIT:",
        "  - Upload CV + extractie AI + situatie posturi agregate",
        "  - Corectare extractie (clientul confirma)",
        "  - Completare chestionare gratuit = insight-uri gratuite",
        "  - Platit: raport compatibilitate cu post (GRATUIT cand vine de la matching B2B)",
        "  - Platit: consiliere prezentare interviu",
        "  - Platit: ghid 'cum sa-ti alegi joburile'",
        "",
        "Card 2 (Relatii) — PLATIT (activare cu credite):",
        "  - Mini-chestionar relational gratuit la activare",
        "  - Platit: harta relatiilor + consiliere imbunatatire",
        "  - Comunitate: acces conditionat de nivel (agent calibreaza)",
        "",
        "Card 4 (Succes vs Valoare) — PLATIT:",
        "  - Dialog Coach + mini-chestionar",
        "  - Platit: evaluare VIA aprofundata + plan dezvoltare virtuti",
        "  - Platit: sesiuni coaching ghidate",
        "",
        "Card 1 (Drumul catre mine) — PLATIT:",
        "  - Dialog Calauza + mini-chestionar",
        "  - Platit: sesiuni continue, exercitii SVHA, journaling ghidat",
        "  - Platit: profil aprofundat + plan evolutie",
        "  - La momentul potrivit: recomandare calauze umane (parteneriate viitoare)",
        "",
        "Card 5 (Antreprenoriat transformational) — PLATIT:",
        "  - Sinteza traseului pe carduri",
        "  - Platit: coaching integrativ, plan actiune transformational",
        "",
        "PUNTE B2B-B2C (matching recrutare):",
        "  - B2C primeste GRATUIT raportul compatibilitate cand vine matching B2B",
        "  - B2C plateste consiliere interviu pas 2",
        "  - B2B plateste raportul compatibilitate candidat",
        "",
        "COMUNITATI (5):",
        "  - Acces inclus in activarea cardului (nu separat)",
        "  - Dar CONDITIONAT de nivel (agentul calibreaza readiness)",
        "",
        "2. PROPUNERI PRET:",
        "  - Propune preturi in RON per serviciu (credite)",
        "  - Strategie: preturi MICI la B2C = volum = masa critica",
        "  - Referinta: docs/pricing-strategy-guide.md + docs/cost-per-interaction-analysis.md",
        "  - Tine cont de costul AI per interactiune (~$0.02-0.04/mesaj)",
        "  - Gandeste pachete: explorer (1 card), adventurer (3 carduri), transformer (toate 5)",
        "",
        "3. INTEGRARE IN PLANUL DE MARKETING:",
        "  - Trimite structura servicii + pricing catre MKA pentru integrare in planul marketing",
        "  - B2C si B2B trebuie sa fie in acelasi plan, nu separate",
        "  - Puntea B2B-B2C e diferentiator cheie in marketing",
        "  - Referral dual (brainstorm in pipeline) se integreaza aici",
        "",
        "CONTEXT COMPLET: docs/situatie-completa-b2b-b2c-03apr2026.md",
        "",
        "LIVRABIL: Document structura servicii B2C cu pricing propus + integrare in plan marketing.",
      ].join("\n"),
      rationale: "Owner solicita structura servicii B2C cu pricing, integrata in planul marketing. Design B2C complet disponibil.",
      changeSpec: {
        action: "B2C_PRICING",
        assignTo: ["PMA", "MKA", "ACA", "COG"],
        deadline: "2026-04-18",
        priority: "HIGH",
        reference: "docs/situatie-completa-b2b-b2c-03apr2026.md",
      },
    },
  })
  process.stdout.write("1. " + p1.title + "\n")

  // 2. Propunere MKA — integrare B2C in plan marketing
  const p2 = await prisma.orgProposal.create({
    data: {
      proposalType: "MODIFY_OBJECTIVES",
      status: "DRAFT",
      proposedBy: "CLAUDE",
      title: "Integrare servicii B2C in planul de marketing unitar B2B+B2C",
      description: [
        "MKA + ACA + CMA + CWA + ACEA:",
        "",
        "TASK: Integrati structura de servicii B2C (care va veni de la PMA) in planul de marketing.",
        "",
        "PUNCTE CHEIE:",
        "- Planul de marketing trebuie sa fie UNITAR (B2B + B2C in aceeasi poveste)",
        "- Puntea B2B-B2C (matching recrutare) e diferentiator UNIC pe piata",
        "- B2B ofera posturi, B2C ofera candidati — JobGrade intermediaza cu valoare",
        "- Povestea: 'Incepem cu CINE alegi sa FII... Evoluam impreuna!'",
        "- Pricing B2C: mic, accesibil, volum — 'gratuit ce-l aduce la masa, platit ce-l ajuta sa castige'",
        "",
        "CANALE B2C specifice:",
        "- Social media: LinkedIn (profesionisti), Instagram/TikTok (tineri, cariera)",
        "- Content: articole despre auto-cunoastere, cariera, relatii (nu despre platforma)",
        "- Referral: fluturele aduce crisalida (program referral din brainstorm)",
        "- Email: alias@jobgrade.ro ca canal organic",
        "- Comunitati: dupa masa critica, promovare organica",
        "",
        "DIFERENTIATORI DE COMUNICAT:",
        "- Echipa mixta AI + psihologi reali (CPR acreditat)",
        "- Anonimizare totala (pseudonim, email propriu)",
        "- 6 carduri concentrice — de la sine la lume",
        "- Dialog-centric — nu formulare, ci conversatie",
        "- Spirala invatarii — progres vizibil, masurabil",
        "- SVHA holistic — fizic, mental, emotional, spiritual",
        "",
        "REFERINTE:",
        "- docs/situatie-completa-b2b-b2c-03apr2026.md (situatia completa)",
        "- docs/pricing-strategy-guide.md",
        "- docs/brief-creativ-comercial-3-pagini.md",
        "",
        "LIVRABIL: Plan marketing actualizat cu sectiunea B2C integrata + timeline lansare B2C.",
      ].join("\n"),
      rationale: "Planul de marketing trebuie sa fie unitar B2B+B2C, cu puntea ca diferentiator",
      changeSpec: {
        action: "MARKETING_B2C_INTEGRATION",
        assignTo: ["MKA", "ACA", "CMA", "CWA", "ACEA"],
        deadline: "2026-04-20",
        dependsOn: "B2C_PRICING (PMA)",
      },
    },
  })
  process.stdout.write("2. " + p2.title + "\n")

  await prisma.$disconnect()
  process.stdout.write("\nDONE — 2 propuneri delegate (PMA pricing + MKA integrare marketing)\n")
}

main()
